### PR TITLE
Add functional logic for specific gravity adjustments

### PR DESCRIPTION
**Pull request by Sparrow0hawk**
This PR introduces functional logic for calculating adjustments to weight/volume based on the specific gravity of the food.
It works by taking a row from a dataframe (our inferred input data source) and perform a series of checks which then dispatch to other functions. These dispatches are match/if statements that check the value of the indicator columns to decide which additional functions to fire. This aims to reduce the nested `ifelse` logic in the original [NPMCalculator app](https://github.com/Leeds-CDRC/NPM-Calculator/blob/main/server.R#L149-L173).

This PR also introduces unit tests for this function which will be incorporated into an automated test suite.

### CODE REVIEW

**Comment by Sparrow0hawk** [comment]
@peterbaudains would you be able to add @VJenneson to this repo so I can add her as a reviewer? Thanks!

**Comment by Sparrow0hawk** [comment]
On thinking about this, the current implementation is very coupled to the idea we're passing a data frame row with specific format columns. It would be way nicer to uncouple the actual SG conversion functions to just take values and any additional required type parameters to determine behaviour.

We can then just change the implementation of the SGConverter high level function to pass in these specific rows at dispatch so that people could use the low level API more flexible v the app itself.

**Comment by peterbaudains** [comment]
> @peterbaudains would you be able to add @VJenneson to this repo so I can add her as a reviewer? Thanks!

All done

**Comment by Sparrow0hawk** [comment]
Hi @VJenneson, this is a quick snapshot of some of the work i've been doing, looking specifically at the specific gravity transformations.

At the moment it's assuming we're passing in the row of a data.frame (but this is something I intend to revisit for the low level functions to make it easier to use if people directly interact with the R package).

If you want to have a go I think the easiest way would be to spin up a GitHub codespace on this repo (Go back to the repo page, click the green <> Code button > Codespaces tab > Create a codespace on main

This will spin up a small cloud compute instance on the repo in which you can run:

```bash
# checkout the specific gravity code
git checkout AC-add-specific-gravity-logic

# start an R console
R

# load devtools
> library(devtools)
# load the package
> load_all()
# use SGConverter function
> SGConverter
```
You should be able to upload data or create a dummy dataframe in R which you can test it with. 

Let me know how you get on/if you need any help.

**Pull request merged**
